version: '3.3'

volumes:
  redis-data:

services:
  app:
    container_name: fastapi-app
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  worker:
    build: ./
    container_name: celery-worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
